### ISSUE TITLE
[16.0][BUG] PDF Viewer Header Overlap Issue

### ISSUE THREAD

**Issue by TheClaud99** [OCA/sign#43]
## Module
sign_oca

## Describe the bug
When scrolling to the bottom of the PDF document, the header overlaps with the content, causing the bottom part of the document to be cut off and obscured from view.

This is proved by the scrollbar which goes out of the screen
![image](https://github.com/OCA/sign/assets/39127925/f91e7a4a-d4f6-48b7-8309-8b468e9a8be6)

When I remove the header from the inspector I can see the entire document correctly
![image](https://github.com/OCA/sign/assets/39127925/d3a8ec67-7fec-455f-8db4-d7c875a7c77e)
![image](https://github.com/OCA/sign/assets/39127925/51cbd969-e793-40ba-9474-e3bbfe8c3630)

## To Reproduce
**Affected versions**:
16.0 (don't check on other versions)

1. Open a pdf to sign
2. Try to scroll to the very bottom of the document

**Expected behavior**
The entire content of the PDF should be visible, including the bottom part, without any part being obscured by the header.

**Additional context**)
Odoo version: 16.0-20240417

**Comment by LuisVPB** [comment]
I experienced the logo overlapping issue in Odoo 16.0 Community. Although Runboat seems to have a fix, my local installation (recently cloned) still showed a very large logo that covered the document.

My findings: The issue is highly sensitive to the image's aspect ratio. I managed to fix it by uploading a logo with a smaller height/wider aspect ratio. However, to make the module more robust, I suggest ensuring a max-height (e.g., 60px) is explicitly set in the sign_oca_pdf_portal.xml template to prevent scaling issues with different company logos.
